{
  "addons": {
    "apt": {
      "sources": [
        "ubuntu-toolchain-r-test",
	"llvm-toolchain-precise-3.7"
      ],
      "packages": [
        "gcc-4.8",
        "g++-4.8",
        "clang",
	"libc++-dev",
        "mingw-w64",
        "mingw-w64-dev",
        "mingw-w64-tools",
        "binutils-mingw-w64"
      ]
    }
  },
  "install": [
    ". ./buildall",
  ],
  "language": "cpp",
  "script": [
    "find -wholename 'build-*/starve-check*' -exec '{}' ';'"
  ],
  "sudo": false
}
