#!/bin/bash
if [ "$1" = "" ]; then
	rm -r build-*
	find toolchains -name '*.cmake' \
		-exec bash -c \
		'CUSTOM_COMPILER=$(basename "{}" .cmake) scripts/setcompiler' \
		';'

	echo '---------------- Result '
	ls build-*
	rm ./out/*
	for n in $(find -name '*.deb' | grep -v 'CPack'); do T="${n//\//-}"; mv "$n" "out/${T:13}"; done
elif [ -f "./toolchains/$1.cmake" ]; then
	rm -r build-$1
	CUSTOM_COMPILER=$1 scripts/setcompiler
else
	echo Invalid build name: $1, must be one of:
	find toolchains -name '*.cmake' \
		-exec basename '{}' '.cmake' ';'
fi

