set(CMAKE_SYSTEM_NAME Linux)

set(CMAKE_AR "gcc-ar" CACHE STRING "Use gcc AR")
set(CMAKE_RANLIB "gcc-ranlib" CACHE STRING "Use gcc RANLIB")
set(CMAKE_CXX_FLAGS "-m32" CACHE STRING "Use gcc RANLIB")

set(CMAKE_CXX_COMPILER g++-4.9)
set(CMAKE_C_COMPILER gcc-4.9)
