set(CMAKE_SYSTEM_NAME Windows)

set(CMAKE_AR "i686-w64-mingw32-ar" CACHE STRING "Use gcc AR")
set(CMAKE_RANLIB "i686-w64-mingw32-ranlib" CACHE STRING "Use gcc RANLIB")

set(CMAKE_CXX_COMPILER i686-w64-mingw32-g++)
set(CMAKE_C_COMPILER i686-w64-mingw32-gcc)
set(CMAKE_RC_COMPILER i686-w64-mingw32-windres)

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
