#!/bin/bash
set -ev

cmake --version
mkdir build-$CUSTOM_COMPILER
cd build-$CUSTOM_COMPILER
echo dir:
pwd
cmake -D"CMAKE_TOOLCHAIN_FILE=../toolchains/${CUSTOM_COMPILER}.cmake" ..
make VERBOSE=1 && make package

# "CUSTOM_COMPILER=gcc-64",
# "CUSTOM_COMPILER=gcc-32",
# "CUSTOM_COMPILER=clang-64",
# "CUSTOM_COMPILER=clang-32",
# "CUSTOM_COMPILER=mingw32-64",
# "CUSTOM_COMPILER=mingw32-32"
