#!/bin/bash
set -ev

cmake --version
mkdir build
cd build
cmake -D"CMAKE_TOOLCHAIN_FILE=../toolchain/${CUSTOM_COMPILER}.cmake" ..
make VERBOSE=1

# "CUSTOM_COMPILER=gcc-64",
# "CUSTOM_COMPILER=gcc-32",
# "CUSTOM_COMPILER=clang-64",
# "CUSTOM_COMPILER=clang-32",
# "CUSTOM_COMPILER=mingw32-64",
# "CUSTOM_COMPILER=mingw32-32"
